exports.home_data = {
   homeTitle: 'Enhance your software quality without losing momentum',
   homeSubheader: 'We provide holistic, end-to-end testing solutions that reduce costs & increase efficiency to uphold business continuity',
   homeButton: 'LEARN MORE',
   logos: 4,
   serviceTitle: 'Recommended Testing Services for Healthcare Companies',
   services: 4,
   whyAbstracta: 'Why Abstracta?',
   whyAbstractaElems: 4,
   ourToolbelt: 'Our Toolbelt',
   ourToolbeltLogos: 15,
   featuredInsights: 'Featured Insights',
   featuredInsightsElems: 3,
   featuredCaseStudies: 'Featured Case Studies',
   featuredCaseStudiesElems: 3,
   whatOthersSay: 'What Others Say',
   contact: "Contact Us",
   formTitle: 'Get in Touch',
   solutions: 'Solutions',
   solutionsElems: 6,
   whyUs: "Why Abstracta?",
   whyUsElems: 4,
   awards: 4,
   backgroundsImgs: 2
}
