name: Run tests in container

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://juanpasobral/wdiotestrunner:chrometest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        ls
        npm install
    - name: Run tests
      run: |
        ls
        export ENV=qa
        npx wdio wdio.conf.js
