name: Run tests in container

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://juanpasobral/wdiotestrunner:chrometest
    steps:
    - name: Change directories
      run: |
        cd /__w/wdio-abstracta
        ls
    - name: Install dependencies
      run: |
        ls
        npm install
    - name: Run tests
      run: |
        ls
        npx wdio wdio.conf.js
